### ISSUE TITLE
Don't buy anything from this person, they run spam bots on mastodon

### ISSUE THREAD

**Issue by thibaultmol** [Hezuikn/muse-s#1]
this person is actively creating multiple accounts to randomly mention links to their product on mastodon. avoid!

![image](https://github.com/user-attachments/assets/8699fd64-fdbe-46a3-a83e-fddb60649177)

![image](https://github.com/user-attachments/assets/f43b3a22-1a4a-41b9-9ae3-6b82d802e2dd)

![image](https://github.com/user-attachments/assets/118583dd-9508-4690-8a21-69cf982fa767)

![image](https://github.com/user-attachments/assets/f05f307a-a322-4a31-8c80-b809b00702d0)

**Comment by ninstar** [comment]
Have to say, this is probably one of the most bizarre spam bots I've seen in a while.

**Comment by takouhai** [comment]
this user is also spamming from [`@cbbew@mstdn.jp`](https://mstdn.jp/@cbbew)

![IMG_0532](https://github.com/user-attachments/assets/7702a962-b880-4807-82a1-7e9435cb4396)

i've already reported them to `mstdn.jp` and reported this repository as spam to github.

**Comment by ExperiencersInternational** [comment]
> Have to say, this is probably one of the most bizarre spam bots I've seen in a while.

Yeah, I love how they're so openly linking one of their GitHub repos too. Thankfully it's been temporarily limited on one of the servers I'm on, but I can't actually report from my main server 😭

**Comment by Hezuikn** [comment]
closing this as "wontfix" lmao, i actually won btw if you care

**Comment by ninstar** [comment]
> closing this as "wontfix" lmao, i actually won btw if you care

You didn't even close it...

**Comment by Hezuikn** [comment]
make sure to star the repo!

**Comment by Hezuikn** [comment]
> this person is actively creating multiple accounts to randomly mention links to their product on mastodon. avoid!

the fuck do you mean _my_ product, do i look like i run that company?

**Comment by Hezuikn** [comment]
pathetic no you

**Comment by ExperiencersInternational** [comment]
Surely you have better things to do online than spam accounts with a link to a headband or something?

You could work for it in some way...
